global:
  scrape_interval: 1s
  evaluation_interval: 1s
  external_labels:
    monitor: 'promethus'

rule_files:
 - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - ec2-18-205-162-195.compute-1.amazonaws.com:9100
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: access_key
        secret_key: secret_key
        port: 9100
